#!/usr/bin/env python3
"""Generate lightweight oral-training index views from record metadata.

This script intentionally uses only Python stdlib and a small YAML-front-matter parser.
"""

from __future__ import annotations

from collections import defaultdict
from pathlib import Path
from typing import Any, Iterable

from _record_utils import iter_records, meta_date

ROOT = Path(__file__).resolve().parents[2]
MODULE = ROOT / "oral_training"
RECORDS = MODULE / "records"
VIEWS = MODULE / "views"


def as_list(value: Any) -> list[str]:
    if value is None or value == "":
        return []
    if isinstance(value, list):
        return [str(x) for x in value if str(x)]
    return [str(value)]


def safe_name(text: str) -> str:
    text = text.strip() or "unknown"
    for ch in "\\/:*?\"<>| ":
        text = text.replace(ch, "_")
    while "__" in text:
        text = text.replace("__", "_")
    return text.strip("_") or "unknown"


def record_row(path: Path, meta: dict[str, Any]) -> str:
    rel = path.relative_to(MODULE).as_posix()
    link = "../../" + rel
    date = meta.get("date", "")
    source = meta.get("source", "")
    problem = meta.get("problem", path.stem)
    title = meta.get("title", "")
    verdict = meta.get("verdict", "")
    mistakes = ", ".join(as_list(meta.get("misjudgment_tags")))
    return f"| {date} | [{problem}]({link}) | {title} | {source} | {verdict} | {mistakes} |"


def write_index(path: Path, title: str, records: Iterable[tuple[Path, dict[str, Any]]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    rows = [record_row(p, m) for p, m in sorted(records, key=lambda x: (str(x[1].get("date", "")), x[0].as_posix()))]
    content = [f"# {title}", "", "<!-- generated by oral_training/scripts/index_records.py -->", ""]
    content.append("| Date | Problem | Title | Source | Verdict | Mistakes |")
    content.append("|---|---|---|---|---|---|")
    content.extend(rows)
    content.append("")
    path.write_text("\n".join(content), encoding="utf-8")


def rating_bucket(value: Any) -> str:
    try:
        rating = int(value)
    except Exception:  # noqa: BLE001
        return "unknown"
    lo = (rating // 400) * 400
    hi = lo + 399
    return f"{lo}-{hi}"


def main() -> None:
    records = list(iter_records(RECORDS))

    by_oj: dict[str, list[tuple[Path, dict[str, Any]]]] = defaultdict(list)
    by_tag: dict[str, list[tuple[Path, dict[str, Any]]]] = defaultdict(list)
    by_time: dict[str, list[tuple[Path, dict[str, Any]]]] = defaultdict(list)
    by_rating: dict[str, list[tuple[Path, dict[str, Any]]]] = defaultdict(list)

    for path, meta in records:
        by_oj[safe_name(str(meta.get("source", "unknown")))].append((path, meta))
        for tag in set(as_list(meta.get("initial_tags")) + as_list(meta.get("official_tags"))):
            by_tag[safe_name(tag)].append((path, meta))
        d = meta_date(meta)
        if d is not None:
            iso = d.isocalendar()
            by_time[f"{iso.year}-W{iso.week:02d}"].append((path, meta))
            by_time[d.strftime("%Y-%m")].append((path, meta))
        by_rating[rating_bucket(meta.get("rating"))].append((path, meta))

    for key, items in by_oj.items():
        write_index(VIEWS / "oj" / f"{key}.md", f"OJ: {key}", items)
    for key, items in by_tag.items():
        write_index(VIEWS / "tags" / f"{key}.md", f"Tag: {key}", items)
    for key, items in by_time.items():
        write_index(VIEWS / "time" / f"{key}.md", f"Time: {key}", items)
    for key, items in by_rating.items():
        write_index(VIEWS / "rating" / f"{key}.md", f"Rating: {key}", items)

    print(f"Indexed {len(records)} record(s).")


if __name__ == "__main__":
    main()
